CREATE TABLE IF NOT EXISTS galoshesdb.categories (
  ID INT NOT NULL AUTO_INCREMENT,
  NODE_NAME VARCHAR(50) NOT NULL,
  NODE_DESCRIPTION VARCHAR(50) NOT NULL,
  PARENT_ID INT,
  PRIMARY KEY (ID))
ENGINE = InnoDB;